class AppStrings {
  static const Map<String, Map<String, String>> _values = {
    'es': {
      /// Login y Register
      'login_title': 'GESTOR DE INVERSIONES',
      'login_error': 'Error al loguearse',
      'reg_title': 'NUEVA CUENTA',
      'user': 'Usuario',
      'pass': 'Contraseña',
      'email': 'Email',
      'btn_access': 'ACCEDER',
      'btn_create': 'CREAR CUENTA',
      'no_account': '¿No tienes cuenta? Regístrate aquí',
      'req_conn': '(Requiere conexión)',
      'fields_req': 'Todos los campos son obligatorios',
      'reg_success': '¡Usuario registrado!',

      /// Home y Portfolio
      'portfolio': 'MI CARTERA',
      'active': 'ACTIVO',
      'qty': 'CANT.',
      'value': 'VALOR',
      'pnl': 'PnL %',
      'sync_pending': 'PENDIENTE SYNC',
      'empty': 'Cartera vacía',
      'logout_tooltip': 'Cerrar sesión',
      'sync_tooltip': 'Sincronizado con la base de datos',
      'offline_tooltip': 'Modo local: Sin conexión',
      'syncing_msg': 'Sincronizando con MariaDB...',
      'offline_msg': 'Modo Offline: Usando base de datos local',
      'delete_title': '¿Eliminar ',
      'cancel': 'CANCELAR',
      'delete': 'BORRAR',

      'tab_all': 'TODO',
      'tab_stocks': 'ACCIONES',
      'tab_cryptos': 'CRIPTOS',
      'tab_currencies': 'DIVISAS',

      'transaction_success': 'Operación realizada con exito',
      'transaction_error': 'Error al realizar la operación',
      'transaction_deleted': 'Operación borrada',

      /// Add Item
      'new_inv': 'NUEVA INVERSIÓN',
      'cat_label': '1. CATEGORÍA',
      'cat_hint': 'Selecciona categoría',
      'asset_label': '2. ACTIVO',
      'asset_hint': 'Selecciona activo',
      'asset_wait': 'Elige categoría primero',
      'qty_label': 'CANTIDAD (> 0)',
      'price_label': 'PRECIO (€ > 0)',
      'btn_confirm': 'CONFIRMAR OPERACIÓN',
      'btn_incomplete': 'COMPLETA LOS DATOS',

      /// Totals y Details
      'total_res': 'RESUMEN GENERAL',
      'total_val': 'VALOR TOTAL',
      'init_inv': 'Inversión Inicial',
      'abs_pnl': 'Ganancia/Pérdida Absoluta',
      'perc_pnl': 'Rendimiento Porcentual',
      'avg': 'Media',
      'current': 'Actual',
    },
    'gl': {
      'login_title': 'XESTOR DE INVERSIÓNS',
      'login_error': 'Error logueando',
      'reg_title': 'NOVA CONTA',
      'user': 'Usuario',
      'pass': 'Contrasinal',
      'email': 'Email',
      'btn_access': 'ACCEDER',
      'btn_create': 'CREAR CONTA',
      'no_account': 'Non tes conta? Rexístrate aquí',
      'req_conn': '(Precisa conexión)',
      'fields_req': 'Todos os campos son obrigatorios',
      'reg_success': 'Usuario rexistrado!',
      'portfolio': 'A MIÑA CARTEIRA',
      'active': 'ACTIVO',
      'qty': 'CANT.',
      'value': 'VALOR',
      'pnl': 'PnL %',
      'sync_pending': 'PENDENTE SYNC',
      'empty': 'Carteira baleira',
      'logout_tooltip': 'Pechar sesión',
      'sync_tooltip': 'Sincronizado coa base de datos',
      'offline_tooltip': 'Modo local: Sen conexión',
      'syncing_msg': 'Sincronizando con MariaDB...',
      'offline_msg': 'Modo Offline: Usando base de datos local',
      'delete_title': 'Eliminar ',
      'cancel': 'CANCELAR',
      'delete': 'BORRAR',

      'transaction_success': 'Operación realizada con exito',
      'transaction_error': 'Error realizando a operación',
      'transaction_deleted': 'Operación borrada',

      'tab_all': 'TODO',
      'tab_stocks': 'ACCIÓN S',
      'tab_cryptos': 'CRIPTOS',
      'tab_currencies': 'DIVISAS',

      'new_inv': 'NOVA INVERSIÓN',
      'cat_label': '1. CATEGORÍA',
      'cat_hint': 'Selecciona categoría',
      'asset_label': '2. ACTIVO',
      'asset_hint': 'Selecciona activo',
      'asset_wait': 'Elixe categoría primeiro',
      'qty_label': 'CANTIDADE (> 0)',
      'price_label': 'PREZO (€ > 0)',
      'btn_confirm': 'CONFIRMAR OPERACIÓN',
      'btn_incomplete': 'COMPLETA OS DATOS',
      'total_res': 'RESUMO XERAL',
      'total_val': 'VALOR TOTAL',
      'init_inv': 'Inversión Inicial',
      'abs_pnl': 'Ganancia/Pérdida Absoluta',
      'perc_pnl': 'Rendemento Porcentual',
      'avg': 'Media',
      'current': 'Actual',
    },
    'en': {
      'login_title': 'INVESTMENT MANAGER',
      'login_error': 'Error logging in',
      'reg_title': 'NEW ACCOUNT',
      'user': 'Username',
      'pass': 'Password',
      'email': 'Email',
      'btn_access': 'LOGIN',
      'btn_create': 'CREATE ACCOUNT',
      'no_account': 'Don\'t have an account? Register here',
      'req_conn': '(Connection required)',
      'fields_req': 'All fields are required',
      'reg_success': 'User registered!',
      'portfolio': 'MY PORTFOLIO',
      'active': 'ASSET',
      'qty': 'QTY.',
      'value': 'VALUE',
      'pnl': 'PnL %',
      'sync_pending': 'SYNC PENDING',
      'empty': 'Empty portfolio',
      'logout_tooltip': 'Logout',
      'sync_tooltip': 'Synced with database',
      'offline_tooltip': 'Offline mode',
      'syncing_msg': 'Syncing with MariaDB...',
      'offline_msg': 'Offline Mode: Using local database',
      'delete_title': 'Delete ',
      'cancel': 'CANCEL',
      'delete': 'DELETE',

      'transaction_success': 'Transaction completed successfully',
      'transaction_error': 'Error completing transaction',
      'transaction_deleted': 'Transaction deleted',

      'tab_all': 'ALL',
      'tab_stocks': 'STOCKS',
      'tab_cryptos': 'CRYPTOS',
      'tab_currencies': 'FOREX',

      'new_inv': 'NEW INVESTMENT',
      'cat_label': '1. CATEGORY',
      'cat_hint': 'Select category',
      'asset_label': '2. ASSET',
      'asset_hint': 'Select asset',
      'asset_wait': 'Pick category first',
      'qty_label': 'QUANTITY (> 0)',
      'price_label': 'PRICE (€ > 0)',
      'btn_confirm': 'CONFIRM OPERATION',
      'btn_incomplete': 'COMPLETE DATA',
      'total_res': 'GENERAL SUMMARY',
      'total_val': 'TOTAL VALUE',
      'init_inv': 'Initial Investment',
      'abs_pnl': 'Absolute Profit/Loss',
      'perc_pnl': 'Percentage Yield',
      'avg': 'Average',
      'current': 'Current',
    },
  };

  static String get(String key, String lang) {
    return _values[lang]?[key] ?? _values['es']![key]!;
  }
}
